Repository beyond-sw-camp/be10-1st-techsmith-catchclass, pull requests merged in 2024-07, with the labels that each got.

#1 docs: 기능 개발 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/🚀기능-개발-요청.md
Labels: documentation

#15 feat: 전체 테이블 ddl 구문 작성, 각 테이블 테스트 데이터 추가
  catch-class/ddl.sql
  catch-class/test_data.sql
Labels: enhancement

#25 feat: [#4] 회원가입 기능 구현
  catch-class/users/join.sql
Labels: enhancement

#28 docs: #27 erd 추가
  catch-class/erd.damx
Labels: documentation

#31 feat : #29 community insert, update시 사용 trigger
  community/trigger_comments.sql
  community/trigger_post.sql
Labels: enhancement

#34 feat: [#7] 회원 정보 수정
  catch-class/users/editUserInfo.sql
Labels: enhancement

#52 feat: #9 내 정보 조회
  catch-class/users/readUserInfo.sql
Labels: enhancement

#53 feat: #3 게시글 작성
  community/post/postInsert.sql
Labels: enhancement

#56 feat: #30 클래스 정보 조회
  catch-class/class/read_list.sql
Labels: enhancement

#59 feat: #18 게시물 삭제
  community/postDelete.sql
Labels: enhancement

#33 docs : #32 Readme 작성
  README.md
  image/ERD.jpg
  image/WBS.jpg
  image/logo.jpeg
  image/광주 취미활동.jpg
  image/노인 학습 1.jpg
  image/논리.jpg
  image/물리영역.jpg
  image/취미활동 자료.jpg
  image/취미활동 좋아.jpg
  image/테스트케이스.jpg
Labels: documentation

#60 fix: 경로 바꿈
  community/post/postDelete.sql
Labels: enhancement

#64 docs: readme 이미지 수정
  README.md
Labels: documentation

#58 fix: ddl 구문 및 테스트 데이터 수정
  catch-class/ddl.sql
  catch-class/test_data.sql
Labels: enhancement

#55 feat: #11 아이디 찾기
  catch-class/users/findId.sql
Labels: enhancement

#65 feat: #62 쿠폰 등록
  catch-class/coupon/createCoupon.sql
Labels: enhancement

#61 feat: #13 비밀번호 찾기
  catch-class/users/findPwd.sql
Labels: enhancement

#74 feat: #5 게시물 조회
  community/post/postList.sql
Labels: enhancement

#76 feat : 후기 조회 기능 추가
  catch-class/review/viewreviews/viewreviews.sql
Labels: enhancement

#72 feat: #70 회원의 예약 내역 조회 기능 개발
  catch-class/reservation/readList.sql
Labels: enhancement

#78 feat: #14 회원 탈퇴
  catch-class/users/deleteUser.sql
Labels: enhancement

#79 feat: #14 사업자 인증 신청
  catch-class/users/registerCert.sql
Labels: enhancement

#88 feat: #87 사업자 인증 신청 내역 조회
  catch-class/admin/checkCert.sql
Labels: enhancement

#90 feat: #89 사업자 인증 승인여부 결정
  catch-class/admin/confirmCert.sql
Labels: enhancement

#73 feat: #68 쿠폰 조회
  catch-class/coupon/readCoupon.sql
Labels: enhancement

#84 feat: #26 게시물 신고
  community/post/postReport.sql
Labels: enhancement

#110 feat: #109 회원이 예약한 원데이클래스 상세 내역 조회 기능 개발
  catch-class/reservation/readDetail.sql
Labels: enhancement

#105 feat: #104 신고 내역 상세 조회
  catch-class/admin/selectReportDetail.sql
Labels: enhancement

#93 feat: #92 신고 내역 목록 조회
  catch-class/admin/selectReportAll.sql
Labels: enhancement

#97 feat: #96 신고 처리
  catch-class/admin/handleReport.sql
Labels: enhancement

#77 feat: #10 게시글 수정
  community/post/postUpdate.sql
Labels: enhancement

#98 feat: #45 후기 등록 기능 구현
  catch-class/review/addReview.sql
  catch-class/review/viewreviews.sql
Labels: enhancement

#111 feat: #50 좋아요 삭제 기능 구현
  catch-class/review/delReviewHits.sql
Labels: enhancement

#112 feat: #49 좋아요 수 조회 기능 구현
  catch-class/review/countReviewHits.sql
Labels: enhancement

#108 feat: #48 좋아요 등록 기능 추가
  catch-class/review/addReviewHits.sql
Labels: enhancement

#103 feat: #46 후기 삭제 기능 추가
  catch-class/review/delReview.sql
Labels: enhancement

#120 feat: #23 댓글 신고
  community/comments/commentReport.sql
Labels: enhancement

#107 feat: #47 후기 신고 기능 추가
  catch-class/review/reportReview.sql
Labels: enhancement

#118 feat: #37 회차(subclass) 정보 등록
  catch-class/class/insertSubclass.sql
Labels: enhancement

#117 feat: #36 클래스 정보 등록
  catch-class/class/insertClass.sql
Labels: enhancement

#149 feat: #148 알림 생성
  catch-class/note/createNote.sql
Labels: enhancement

#122 feat: #20 댓글 수정
  community/comments/commentUpdate.sql
Labels: enhancement

#124 feat: #19 댓글작성
  community/comments/commentInsert.sql
Labels: enhancement

#116 feat: #6 게시물 검색
  community/post/postSearch.sql
Labels: enhancement

#119 feat: #17 게시글 상세 조회
  community/post/postDetail.sql
Labels: enhancement

#123 feat: #39 클래스 정보 수정 기능 구현
  catch-class/class/updateClassInfo.sql
Labels: enhancement

#125 feat: #43 클래스 정보 삭제
  catch-class/class/deleteClassInfo.sql
Labels: enhancement

#152 feat: #150 예약자 목록 조회 기능 개발
  catch-class/reservation/readUserList.sql
Labels: enhancement

#126 feat: #51 클래스 상태 변경
  catch-class/class/updateClassStatus.sql
Labels: enhancement

#153 feat: #151 예약자 상세 조회 기능 개발
  catch-class/reservation/readUserDetail.sql
Labels: enhancement

#155 feat: #154 예약자 출석 상태 변경 기능 개발
  catch-class/reservation/updateAttendanceStatus.sql
Labels: enhancement

#157 feat: #156 예약 취소
  catch-class/reservation/cancelReservation.sql
Labels: enhancement

#127 feat:#69 클래스 문의 등록
  catch-class/class/inquiryClass.sql
Labels: enhancement

#131 feat:#75 클래스 문의 목록 조회
  catch-class/class/getInquiryList.sql
Labels: enhancement

#121 feat: #21 댓글 삭제
  community/comments/commentDelete.sql
Labels: enhancement

#161 feat: #42 후기 최신순 조회 기능 수정
  catch-class/review/viewReviewLatests.sql
Labels: enhancement

#158 feat: #41 후기 조회 별점순 기능 수정
  catch-class/review/viewReviewsRating.sql
Labels: enhancement

#165 commnet: #156 CALL 함수 주석처리 / docs: erd 파일 최신화
  catch-class/erd.damx
  catch-class/erd_tech_smith.damx
Labels: documentation

#162 feat: #91 클래스 문의 상세 조회
  catch-class/class/detailInquiry.sql
Labels: enhancement

#163 feat: #99 클래스 문의 수정
  catch-class/class/updateInquiry.sql
Labels: enhancement

#164 feat: #106 클래스 문의 답변 등록
  catch-class/class/responseInquiry.sql
Labels: enhancement

#166 feat: #102 문의 게시글 상태 변경
  catch-class/class/updateInquiryStatus.sql
Labels: enhancement

#167 feat: #113 클래스 신고
  catch-class/class/reportClass.sql
Labels: enhancement

#132 feat: #128 쿠폰 상태 변경
  catch-class/coupon/updateCouponStatusByName.sql
Labels: enhancement

#134 feat: #129 쿠폰 사용 상태 변경
  catch-class/coupon/updateCouponOwnerStatus.sql
Labels: enhancement

#140 feat: #130 쿠폰 발급
  catch-class/coupon/createCouponOwner.sql
Labels: enhancement

#143 feat: #142 찜하기
  catch-class/bookmark/createBookmark.sql
Labels: enhancement

#147 feat: #146 찜한 목록 조회
  catch-class/bookmark/readBookmarkList.sql
Labels: enhancement

#145 feat: #144 찜하기 취소
  catch-class/bookmark/deleteBookmark.sql
Labels: enhancement

#169 fix: 오류 메시지 수정
  catch-class/bookmark/createBookmark.sql
  catch-class/bookmark/readBookmarkList.sql
Labels: enhancement

#170 comment: #130 CALL 함수 주석 처리
  catch-class/coupon/createCoupon.sql
Labels: enhancement

#173 fix: #172 신고 처리 기능 수정
  catch-class/admin/handleReport.sql
Labels: bug

#175 fix: #20 댓글 수정 탈퇴시 로직 수정
  community/comments/commentUpdate.sql
Labels: enhancement

#176 fix: 주석처리와, 기능 추가
  community/post/postDelete.sql
  community/post/postList.sql
  community/post/postUpdate.sql
Labels: enhancement

#177 fix: community 파일 위치 변경
  catch-class/community/comments/commentDelete.sql
  catch-class/community/comments/commentInsert.sql
  catch-class/community/comments/commentReport.sql
  catch-class/community/comments/commentUpdate.sql
  catch-class/community/post/postDelete.sql
  catch-class/community/post/postDetail.sql
  catch-class/community/post/postInsert.sql
  catch-class/community/post/postList.sql
  catch-class/community/post/postReport.sql
  catch-class/community/post/postSearch.sql
  catch-class/community/post/postUpdate.sql
  catch-class/community/trigger_comments.sql
  catch-class/community/trigger_post.sql
Labels: enhancement

#179 fix: ddl 구문 수정
  catch-class/ddl.sql
Labels: enhancement

#180 fix: 쿠폰 관련 쿼리 일부 수정
  catch-class/coupon/createCouponOwner.sql
  catch-class/coupon/updateCouponStatusByName.sql
Labels: enhancement

#181 docs: erd 최신화
  catch-class/erd_techsmith.damx
Labels: documentation

#184 docs: readme에 플로우 차트 추가
  README.md
  image/플로우차트.png
Labels: documentation

#185 fix: #11 아이디 찾기 기능 수정
  catch-class/users/findId.sql
Labels: bug

#186 fix: #13 비밀번호 찾기 기능 수정
  catch-class/users/findPwd.sql
Labels: bug

#189 fix: readme 충돌 수정
  README.md
  image/논리영역.png
  image/물리영역.png
  image/주제영역.png
  image/테크스미스 요구사항 명세서 - WBS 최종_page-0001.jpg
  image/테크스미스 요구사항 명세서 - 요구사항 명세서_page-0001.jpg
  image/테크스미스 요구사항 명세서 - 테스트케이스 (3)_page-0001.jpg
Labels: documentation

#190 fix: Readme wbs 누락 수정
  README.md
  image/WBS.jpg
Labels: documentation
